docker: remove this line otherwise I have to recompile opencv

diff --git a/raspberrypi_central/smart-camera/build-image/Dockerfile b/raspberrypi_central/smart-camera/build-image/Dockerfile
--- a/raspberrypi_central/smart-camera/build-image/Dockerfile
+++ b/raspberrypi_central/smart-camera/build-image/Dockerfile
@@ -35,7 +35,7 @@ RUN dpkgArch="$(dpkg --print-architecture)"; \
     case "${dpkgArch##*-}" in \
         armv7) pythonArch='arm-linux-gnueabihf'; extra="-D ENABLE_NEON=ON; -D ENABLE_VFPV3=ON" ;; \
         amd64) pythonArch='x86_64-linux-gnu' ;; \
-        *) echo >&2; echo >&2 "error: current architecture ($dpkgArch) is not supported." ;; \
+        # *) echo >&2; echo >&2 "error: current architecture ($dpkgArch) is not supported." ;; \
     esac; \
     cmake -D CMAKE_BUILD_TYPE=RELEASE \
     -D CMAKE_INSTALL_PREFIX=/usr/local \
@@ -58,5 +58,5 @@ RUN dpkgArch="$(dpkg --print-architecture)"; \
         amd64) pythonArch='x86_64-linux-gnu' ;; \
         *) echo >&2; echo >&2 "error: current architecture ($dpkgArch) is not supported." ;; \
     esac; \
-    ln -s /root/opencv/build/lib/python3/cv2.cpython-37$pythonArch.so \
+    ln -s "/root/opencv/build/lib/python3/cv2.cpython-37$pythonArch.so" \
     /usr/local/lib/python3.7/site-packages/cv2.so
